### PR TITLE
Prevent users from being accessable via htaccess

### PR DESCRIPTION
**Pull request by SmilerRyan**
It tells me to move the users out, but adding this file seems to fix the solution. Add this to your project

### CODE REVIEW

**Comment by Zegnat** [comment]
The users directory should already be blocked because of [the main .htaccess](https://github.com/Kroc/NoNonsenseForum/blob/master/.htaccess#L159-L160) (line 159–160):

``` apache
	# don’t allow any access to '/users' (this is accessed purely from the PHP)
	RewriteRule ^users/.*$ - [NC,F]
```

Is this not working for you?

**Comment by SmilerRyan** [comment]
The web servers I used did not seem to block access to the folder, and thus it ignored it.

**Comment by Zegnat** [comment]
> The web servers I used did not seem to block access to the folder, and thus it ignored it.

That’s really odd. Were you using Apache? What version?

If the rest of the forum works, so other `RewriteRule`s from the main .htaccess were applied, I have a hard time seeing why it wouldn’t block access to the users folder.

Did it correctly block the lib folder or were you able to access that one as well?

**Comment by SmilerRyan** [comment]
Strangely enough, the lib folder also seems to be accessible. It seems like it ignores all "-" entries. The file "-" doesn't exist so it skips it, maybe? (I also don't seem to understand why it ignores it).

**Comment by Zegnat** [comment]
> It seems like it ignores all "-" entries. The file "-" doesn't exist so it skips it, maybe?

`-` is not a file or path, it is an instruction to mod_rewrite so it doesn’t actually do any rewriting. The `[F]` flag after it then tells the server to send a Forbidden response and also tells mod_rewrite not to continue with any other rules below it.

This is why it is so puzzling. Obviously mod_rewrite is working for you, else the forum wouldn’t be working, but it also ignores the forbidden commands.

Do you know what version of Apache you are using?

**Comment by Kroc** [comment]
You might also have htaccess behaviour 'leaking' through from a parent folder, or non-default options set by the host.

**Pull request closed without merging**
